server:
  port: 8083

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:shalyanharutyun9@gmail.com}
    password: ${MAIL_PASSWORD:ilcsabxdlbbadwdt}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:CHANGE_ME}
            client-secret: ${GOOGLE_CLIENT_SECRET:CHANGE_ME}
            scope: email,profile

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 3600000

app:
  oauth2:
    redirect-uri: http://localhost:4200/oauth2/redirect