server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/auth/**

        - id: car-service
          uri: ${CAR_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/cars/**

        - id: car-images
          uri: ${CAR_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/images/**

        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/bookings/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/payments/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/notifications/**


jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
