server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: car-service

  datasource:
    url: jdbc:postgresql://localhost:5432/car_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: car-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.carrental.common.event.PaymentCompletedEvent
        spring.json.trusted.packages: "com.carrental.common.event"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

app:
  upload-dir: C:/Users/Harut/Spring/car-rental/car-service/uploads